<a href="https://colab.research.google.com/github/whdlsrltgjqm/ppp/blob/main/%5BLab_session_2%5D_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

np.random.seed(0)

# NumPy Exercises!
Complete the solution code to have a desired output.

**[Caution!]** Not allow to use iteration, such as for-loop.





### 1-1. Create a 5×5 numpy array of all False boolean’s
[ref] [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

In [ ]:
# Input
arr_size = (5, 5)

# Solution
bool_arr = np.full(arr_size, False)

# Print
print(bool_arr)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


### 1-2. Create a 7×7 diagonal matrix with diagonal index as 3.
diagonal matrix: 2-D array with ones on the diagonal and zeros elsewhere.
(hint, ref [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))

In [ ]:
# Input
size = 7

# Solution
np_arr = np.eye(size, k=3)

# Print
print(np_arr)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 2. Extract even numbers from given `arr`

In [ ]:
# Input
arr = np.arange(35)

# Solution
arr = arr[0::2]

# Print
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


### 3. Get the positions where elements of `a` and `b` match
(hint, refer [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).)



In [ ]:
# Input
a = np.array([1, 7, 3, 2, 3, 5, 3, 4, 5, 8, 2, 6, 9])
b = np.array([1, 2, 10, 8, 3, 4, 9, 4, 9, 8, 5, 3, 5])

# Solution
idx = np.where(a==b)

# Print
print(idx)

(array([0, 4, 7, 9]),)


### 4. Find the median, standard deviation, average of iris's `sepallength` (1st column).

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
med, std, avg = np.median(sepallength), np.std(sepallength), np.average(sepallength)

# Print
print(med, std, avg)

5.8 0.8253012917851409 5.843333333333334


### 5. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
(hint, refer [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).)

In [ ]:
# Input
np.random.seed(50)
a = np.random.randint(0, 10, 10)
print('Array: ', a)

# Solution
## Create an all True array
out = np.full(10, True)

## Find the index positions of unique elements
unique_positions = np.unique(a,return_index= True)[1]

## Mark those positions as False
out[unique_positions] = False

print('Duplicate entrie: ', out)

Array:  [0 0 1 4 6 5 6 6 5 2]
Duplicate entrie:  [False  True False False False False  True  True  True False]


# Pandas Exercises!
Complete the solution code to have a desired output.





### 6. Combine `ser1` and `ser2` to form a dataframe.
hint, refer [pd.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)

In [3]:
# Input
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution
df = pd.DataFrame({'A':ser1, 'B':ser2})

# Print
print(df.tail())

    A   B
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25


### 7. Check if `df` has any missing values.
hint, refer [df.isnull](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html)

In [4]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())

# Solution
print('\nIs there any missing value?:', df.isna().any().any())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

### 8. Create a TimeSeries starting `2022-09-01` and 7 weekends (mondays).
hint, refer [pd.date_range](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html)

In [6]:
# Solution
ser = pd.Series(pd.date_range('09-01-2022', periods=7, freq='W-MON'))
print(ser)

0   2022-09-05
1   2022-09-12
2   2022-09-19
3   2022-09-26
4   2022-10-03
5   2022-10-10
6   2022-10-17
dtype: datetime64[ns]


### 9. In `df`, compute the median price of every fruit using grouping function.
hint, refer [df.groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

In [11]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange', 'blueberry', 'melon'] * 5,
                   'rating': np.random.rand(25),
                   'price': np.random.randint(0, 20, 25)})

# Solution
df.groupby('fruit')['price'].median()

fruit
apple        11.0
banana       10.0
blueberry    11.0
melon         7.0
orange        9.0
Name: price, dtype: float64

### 10. Join two dataframes `df1` and `df2` for intersection items on `use_id`.
For `df2`, please select only `use_id`, `platform`, `device` columns not all columns for merging.
hint, refer [pd.merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

In [18]:
# Input
base_path = 'https://raw.githubusercontent.com/shanealynn/Pandas-Merge-Tutorial/master/'
df1 = pd.read_csv(base_path + 'user_usage.csv')
df2 = pd.read_csv(base_path + 'user_device.csv')

# Solution
pd.merge(df1, df2[['use_id', 'platform', 'device']], left_on='use_id', right_on='use_id').head(5)

outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                    21.97                    4.82     1557.33   22787   
1                  1710.08                  136.88     7267.55   22788   
2                  1710.08                  136.88     7267.55   22789   
3                    94.46                   35.17      519.12   22790   
4                    71.59                   79.26     1557.33   22792   

  platform    device  
0  android  GT-I9505  
1  android  SM-G930F  
2  android  SM-G930F  
3  android     D2303  
4  android  SM-G361F